# Generated by Django 4.2.4 on 2023-08-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('short_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='')),
                ('package_type', models.CharField(blank=True, choices=[('B', 'Basic'), ('P', 'Platinum'), ('G', 'Gold')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': "Tour's",
            },
        ),
    ]
