# Generated by Django 4.2.4 on 2023-08-18 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0004_alter_tour_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='agent',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agent Name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AgentList',
        ),
    ]
