# Generated by Django 4.2.4 on 2023-08-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_tour_end_date_alter_tour_package_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_images/')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_pictures',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.tourpicture'),
        ),
    ]
